### ISSUE TITLE
Assertion failed: tried to removeListener on something that wasnt a listener

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#144]
Discovered during testing in https://github.com/phetsims/circuit-construction-kit-dc/issues/143

I was cutting a vertex and saw:
```
Uncaught Error: Assertion failed: tried to removeListener on something that wasnt a listener
    at window.assertions.assertFunction (assert.js:22)
    at Emitter.removeListener (Emitter.js?bust=1503269575062:109)
    at Property.unlink (Property.js?bust=1503269575062:267)
    at Array.linkVertex (CircuitElement.js?bust=1503269575062:130)
    at Emitter.emit2 (Emitter.js?bust=1503269575062:200)
    at Property._notifyListeners (Property.js?bust=1503269575062:204)
    at Property._setAndNotifyListeners (Property.js?bust=1503269575062:193)
    at Property.set (Property.js?bust=1503269575062:140)
    at Battery.replaceVertex (CircuitElement.js?bust=1503269575062:203)
    at Circuit.js?bust=1503269575062:532
```

**Comment by samreid** [comment]
This is not happening every time--not as simple as cutting any junction.

**Comment by samreid** [comment]
Hmmm.. Bayes hasn't been too bothered by it:

![image](https://user-images.githubusercontent.com/679486/29499372-c13d7b0e-85cc-11e7-93fa-4bc4c96fda0b.png)

**Comment by samreid** [comment]
Oops, I just remembered Bayes is not on the branch.

**Comment by samreid** [comment]
On the other hand, fuzzing has gone for a few minutes without any trouble.

**Comment by samreid** [comment]
The fuzzer and I are having trouble reproducing this problem, closing for now.

**Comment by samreid** [comment]
Now I'm hitting this problem from reset:

```
"Error
    at eval (eval at window.assertions.assertFunction (http://localhost/assert/js/assert.js:22:7), <anonymous>:1:9)
    at window.assertions.assertFunction (http://localhost/assert/js/assert.js:22:7)
    at Emitter.removeListener (http://localhost/axon/js/Emitter.js?bust=1503356105589:109:17)
    at Property.unlink (http://localhost/axon/js/Property.js?bust=1503356105589:267:29)
    at Battery.CircuitElement.disposeCircuitElement (http://localhost/circuit-construction-kit-common/js/model/CircuitElement.js?bust=1503356105589:158:55)
    at Battery.dispose (http://localhost/circuit-construction-kit-common/js/model/CircuitElement.js?bust=1503356105589:184:12)
    at Array.<anonymous> (http://localhost/circuit-construction-kit-common/js/model/Circuit.js?bust=1503356105589:127:22)
    at ObservableArray._fireItemRemoved (http://localhost/axon/js/ObservableArray.js?bust=1503356105589:163:18)
    at ObservableArray.remove (http://localhost/axon/js/ObservableArray.js?bust=1503356105589:203:14)
    at Circuit.clear (http://localhost/circuit-construction-kit-common/js/model/Circuit.js?bust=1503356105589:445:32)"
```

**Comment by samreid** [comment]
I cannot figure out where the listeners are getting removed from, perhaps vertex disposal is somehow happening before circuit element disposal?  But it's very difficult to reproduce the problem so I'm going to use a custom guard for now.  Custom guard has been fuzzing for a while with no issue.
