### ISSUE TITLE
Publish RC.1

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#166]
In https://github.com/phetsims/QA/issues/51#issuecomment-337291139 @phet-steele indicated we are ready for RC.1.

**Comment by samreid** [comment]
I'm following the https://github.com/phetsims/phet-info/blob/master/deployment-info/sim_deployment.md and ran into trouble after `grunt deploy-rc`.  I logged in to the build server and got these logs:

```
...
Oct 17 11:00:52 phet-server.int.colorado.edu build-server[141379]: Oct 17 2017 11:00:52 MDT - info: running command: npm update
Oct 17 11:00:57 phet-server.int.colorado.edu build-server[141379]: Oct 17 2017 11:00:57 MDT - info: npm update ran successfully in directory: ../circuit-construction-kit-dc
Oct 17 11:00:57 phet-server.int.colorado.edu build-server[141379]: Oct 17 2017 11:00:57 MDT - info: path to translations XML file = /data/web/static/phetsims/sims/html/circuit-construction-kit-dc/undefined/circuit-construction-kit-dc.xml
Oct 17 11:00:57 phet-server.int.colorado.edu build-server[141379]: fs.js:549
Oct 17 11:00:57 phet-server.int.colorado.edu build-server[141379]: return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
Oct 17 11:00:57 phet-server.int.colorado.edu build-server[141379]: ^
Oct 17 11:00:57 phet-server.int.colorado.edu build-server[141379]: Error: ENOENT: no such file or directory, open '/data/web/static/phetsims/sims/html/circuit-construction-kit-dc/undefined/circuit-construction-kit-dc.xml'
Oct 17 11:00:57 phet-server.int.colorado.edu build-server[141379]: at Error (native)
Oct 17 11:00:57 phet-server.int.colorado.edu build-server[141379]: at Object.fs.openSync (fs.js:549:18)
Oct 17 11:00:57 phet-server.int.colorado.edu build-server[141379]: at Object.fs.readFileSync (fs.js:397:15)
Oct 17 11:00:57 phet-server.int.colorado.edu build-server[141379]: at getLocales (/data/share/phet/phet-repos/perennial/js/build-server/build-server.js:500:28)
Oct 17 11:00:57 phet-server.int.colorado.edu build-server[141379]: at /data/share/phet/phet-repos/perennial/js/build-server/build-server.js:908:31
Oct 17 11:00:57 phet-server.int.colorado.edu build-server[141379]: at /data/share/phet/phet-repos/perennial/js/build-server/build-server.js:335:27
Oct 17 11:00:57 phet-server.int.colorado.edu build-server[141379]: at ChildProcess.exithandler (child_process.js:204:7)
Oct 17 11:00:57 phet-server.int.colorado.edu build-server[141379]: at emitTwo (events.js:87:13)
Oct 17 11:00:57 phet-server.int.colorado.edu build-server[141379]: at ChildProcess.emit (events.js:172:7)
Oct 17 11:00:57 phet-server.int.colorado.edu build-server[141379]: at maybeClose (internal/child_process.js:829:16)
Oct 17 11:00:57 phet-server.int.colorado.edu systemd[1]: build-server.service: main process exited, code=exited, status=1/FAILURE
Oct 17 11:00:57 phet-server.int.colorado.edu systemd[1]: Unit build-server.service entered failed state.
Oct 17 11:00:57 phet-server.int.colorado.edu systemd[1]: build-server.service failed.
Oct 17 11:00:58 phet-server.int.colorado.edu systemd[1]: build-server.service holdoff time over, scheduling restart.
Oct 17 11:00:58 phet-server.int.colorado.edu systemd[1]: Started build-server.service.
Oct 17 11:00:58 phet-server.int.colorado.edu systemd[1]: Starting build-server.service...
Oct 17 11:00:59 phet-server.int.colorado.edu build-server[23366]: Oct 17 2017 11:00:59 MDT - info: Listening on port 16371
Oct 17 11:00:59 phet-server.int.colorado.edu build-server[23366]: Oct 17 2017 11:00:59 MDT - info: Verbose mode: false
```

Note the check for `circuit-construction-kit-dc/undefined/circuit-construction-kit-dc.xml`

Nothing out of the ordinary was reported from `grunt deploy-rc` and it included this part of the URL:
`&locales=*&simName=circuit-construction-kit-dc&version=1.0.0-rc.1`

I'll post a message on Slack to see if anyone is aware of build server issues, then I'll try again.

**Comment by samreid** [comment]
I tried it a 2nd time and got this error:

```
~/github/circuit-construction-kit-dc$ grunt deploy-rc
Running "deploy-rc" task
Warning: Unpushed changes exist for repo circuit-construction-kit-dc. Use --force to continue.

```

Indeed dependencies.json had failed to push.  I pushed it manually.

**Comment by samreid** [comment]
Same problem on 2nd try.  Increasing priority and reassigning to @mattpen in case it is a problem with build server, @jonathanolson & @jbphet in case it is a problem with a translation file and @ariel-phet so he is aware of the problem and for delegation.

**Comment by samreid** [comment]
@mattpen is on the case

**Comment by samreid** [comment]
https://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-rc.1/circuit-construction-kit-dc_en.html published here, and there were failures during the cleanup phase on build server.

**Comment by samreid** [comment]
@mattpen also addressed the cleanup phase error and we tested on https://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc-virtual-lab/1.0.0-rc.1/circuit-construction-kit-dc-virtual-lab_en.html
