### ISSUE TITLE
CT: value failed isValidValue

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-dc#176]
```
circuit-construction-kit-dc : fuzz : require.js : run
Uncaught Error: Assertion failed: value failed isValidValue: [object Object]
Error: Assertion failed: value failed isValidValue: [object Object]
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/assert/js/assert.js:22:13)
    at Object.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Validator.js?bust=1546930661649:75:33)
    at Emitter.assertEmittingValidValues (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Emitter.js?bust=1546930661649:80:21)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Emitter.js?bust=1546930661649:190:72)
    at SimpleDragHandler.endDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/input/SimpleDragHandler.js?bust=1546930661649:317:29)
    at SimpleDragHandler.interrupt (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/input/SimpleDragHandler.js?bust=1546930661649:333:14)
    at VertexNode.interruptInput (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/nodes/Node.js?bust=1546930661649:1920:40)
    at VertexNode.blur (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/accessibility/Accessibility.js?bust=1546930661649:532:18)
    at Function.set focus [as focus] (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/display/Display.js?bust=1546930661649:1718:25)
    at Input.downEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/input/Input.js?bust=1546930661649:1524:33)
id: Bayes Chrome
Approximately 1/7/2019, 10:03:42 PM
circuit-construction-kit-dc : fuzz : require.js : run
Uncaught Error: Assertion failed: value failed isValidValue: [object Object]
Error: Assertion failed: value failed isValidValue: [object Object]
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/assert/js/assert.js:22:13)
    at Object.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Validator.js?bust=1546945691610:75:33)
    at Emitter.assertEmittingValidValues (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Emitter.js?bust=1546945691610:80:21)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Emitter.js?bust=1546945691610:190:72)
    at SimpleDragHandler.endDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/input/SimpleDragHandler.js?bust=1546945691610:317:29)
    at SimpleDragHandler.interrupt (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/input/SimpleDragHandler.js?bust=1546945691610:333:14)
    at WireNode.interruptInput (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/nodes/Node.js?bust=1546945691610:1920:40)
    at WireNode.blur (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/accessibility/Accessibility.js?bust=1546945691610:532:18)
    at Function.set focus [as focus] (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/display/Display.js?bust=1546945691610:1718:25)
    at Input.downEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/input/Input.js?bust=1546945691610:1524:33)
id: Bayes Chrome
Approximately 1/7/2019, 10:03:42 PM
circuit-construction-kit-dc : fuzz : require.js : run
Uncaught Error: Assertion failed: value failed isValidValue: [object Object]
Error: Assertion failed: value failed isValidValue: [object Object]
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/assert/js/assert.js:22:13)
    at Object.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Validator.js?bust=1546951324235:75:33)
    at Emitter.assertEmittingValidValues (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Emitter.js?bust=1546951324235:80:21)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Emitter.js?bust=1546951324235:190:72)
    at SimpleDragHandler.endDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/input/SimpleDragHandler.js?bust=1546951324235:317:29)
    at SimpleDragHandler.interrupt (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/input/SimpleDragHandler.js?bust=1546951324235:333:14)
    at WireNode.interruptInput (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/nodes/Node.js?bust=1546951324235:1920:40)
    at WireNode.blur (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/accessibility/Accessibility.js?bust=1546951324235:532:18)
    at Function.set focus [as focus] (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/display/Display.js?bust=1546951324235:1718:25)
    at Input.downEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/input/Input.js?bust=1546951324235:1524:33)
id: Bayes Chrome
Approximately 1/7/2019, 10:03:42 PM
circuit-construction-kit-dc : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed: value failed isValidValue: [object Object]
Error: Assertion failed: value failed isValidValue: [object Object]
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/assert/js/assert.js:22:13)
    at Object.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Validator.js?bust=1546927501168:75:33)
    at Emitter.assertEmittingValidValues (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Emitter.js?bust=1546927501168:80:21)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Emitter.js?bust=1546927501168:190:72)
    at SimpleDragHandler.endDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/input/SimpleDragHandler.js?bust=1546927501168:317:29)
    at SimpleDragHandler.interrupt (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/input/SimpleDragHandler.js?bust=1546927501168:333:14)
    at WireNode.interruptInput (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/nodes/Node.js?bust=1546927501168:1920:40)
    at WireNode.blur (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/accessibility/Accessibility.js?bust=1546927501168:532:18)
    at Function.set focus [as focus] (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/display/Display.js?bust=1546927501168:1718:25)
    at Input.downEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/input/Input.js?bust=1546927501168:1524:33)
id: Bayes Chrome
Approximately 1/7/2019, 10:03:42 PM
circuit-construction-kit-dc : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed: value failed isValidValue: [object Object]
Error: Assertion failed: value failed isValidValue: [object Object]
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/assert/js/assert.js:22:13)
    at Object.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Validator.js?bust=1546949566719:75:33)
    at Emitter.assertEmittingValidValues (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Emitter.js?bust=1546949566719:80:21)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Emitter.js?bust=1546949566719:190:72)
    at SimpleDragHandler.endDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/input/SimpleDragHandler.js?bust=1546949566719:317:29)
    at SimpleDragHandler.interrupt (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/input/SimpleDragHandler.js?bust=1546949566719:333:14)
    at WireNode.interruptInput (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/nodes/Node.js?bust=1546949566719:1920:40)
    at WireNode.blur (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/accessibility/Accessibility.js?bust=1546949566719:532:18)
    at Function.set focus [as focus] (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/display/Display.js?bust=1546949566719:1718:25)
    at Input.downEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/input/Input.js?bust=1546949566719:1524:33)
id: Bayes Chrome
Approximately 1/7/2019, 10:03:42 PM
circuit-construction-kit-dc : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed: value failed isValidValue: [object Object]
Error: Assertion failed: value failed isValidValue: [object Object]
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/assert/js/assert.js:22:13)
    at Object.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Validator.js?bust=1546957290306:75:33)
    at Emitter.assertEmittingValidValues (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Emitter.js?bust=1546957290306:80:21)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Emitter.js?bust=1546957290306:190:72)
    at SimpleDragHandler.endDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/input/SimpleDragHandler.js?bust=1546957290306:317:29)
    at SimpleDragHandler.interrupt (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/input/SimpleDragHandler.js?bust=1546957290306:333:14)
    at WireNode.interruptInput (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/nodes/Node.js?bust=1546957290306:1920:40)
    at WireNode.blur (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/accessibility/Accessibility.js?bust=1546957290306:532:18)
    at Function.set focus [as focus] (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/display/Display.js?bust=1546957290306:1718:25)
    at Input.downEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/input/Input.js?bust=1546957290306:1524:33)
id: Bayes Chrome
Approximately 1/7/2019, 10:03:42 PM
circuit-construction-kit-dc : xss-fuzz : run
Uncaught Error: Assertion failed: value failed isValidValue: [object Object]
Error: Assertion failed: value failed isValidValue: [object Object]
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/assert/js/assert.js:22:13)
    at Object.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Validator.js?bust=1546937168669:75:33)
    at Emitter.assertEmittingValidValues (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Emitter.js?bust=1546937168669:80:21)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Emitter.js?bust=1546937168669:190:72)
    at SimpleDragHandler.endDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/input/SimpleDragHandler.js?bust=1546937168669:317:29)
    at SimpleDragHandler.interrupt (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/input/SimpleDragHandler.js?bust=1546937168669:333:14)
    at VertexNode.interruptInput (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/nodes/Node.js?bust=1546937168669:1920:40)
    at VertexNode.blur (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/accessibility/Accessibility.js?bust=1546937168669:532:18)
    at Function.set focus [as focus] (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/display/Display.js?bust=1546937168669:1718:25)
    at Input.downEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/input/Input.js?bust=1546937168669:1524:33)
id: Bayes Chrome
Approximately 1/7/2019, 10:03:42 PM
circuit-construction-kit-dc : xss-fuzz : run
Uncaught Error: Assertion failed: value failed isValidValue: [object Object]
Error: Assertion failed: value failed isValidValue: [object Object]
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/assert/js/assert.js:22:13)
    at Object.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Validator.js?bust=1546957075159:75:33)
    at Emitter.assertEmittingValidValues (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Emitter.js?bust=1546957075159:80:21)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Emitter.js?bust=1546957075159:190:72)
    at SimpleDragHandler.endDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/input/SimpleDragHandler.js?bust=1546957075159:317:29)
    at SimpleDragHandler.interrupt (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/input/SimpleDragHandler.js?bust=1546957075159:333:14)
    at VertexNode.interruptInput (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/nodes/Node.js?bust=1546957075159:1920:40)
    at VertexNode.blur (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/accessibility/Accessibility.js?bust=1546957075159:532:18)
    at Function.set focus [as focus] (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/display/Display.js?bust=1546957075159:1718:25)
    at Input.downEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/input/Input.js?bust=1546957075159:1524:33)
id: Bayes Chrome
Approximately 1/7/2019, 10:03:42 PM
```

**Comment by pixelzoom** [comment]
Moved to https://github.com/phetsims/axon/issues/208.
