### ISSUE TITLE
Assertion failed: numberZigZags must be an integer:

### ISSUE THREAD

**Issue by veillette** [phetsims/circuit-construction-kit-dc#179]
```
circuit-construction-kit-dc : fuzz : require.js : load
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: numberZigZags must be an integer: 11.9947
Error: Assertion failed: numberZigZags must be an integer: 11.9947
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1558023795722/assert/js/assert.js:22:13)
    at Shape.zigZagToPoint (https://bayes.colorado.edu/continuous-testing/snapshot-1558023795722/kite/js/Shape.js?bust=1558027964641:353:17)
    at new FuseNode (https://bayes.colorado.edu/continuous-testing/snapshot-1558023795722/circuit-construction-kit-common/js/view/FuseNode.js?bust=1558027964641:63:10)
    at CircuitElementToolFactory.createFuseToolNode (https://bayes.colorado.edu/continuous-testing/snapshot-1558023795722/circuit-construction-kit-common/js/view/CircuitElementToolFactory.js?bust=1558027964641:324:9)
    at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1558023795722/circuit-construction-kit-dc/js/intro/view/IntroScreenView.js?bust=1558027964641:41:35)
    at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1558023795722/circuit-construction-kit-dc/js/intro/IntroScreen.js?bust=1558027964641:64:18)
    at IntroScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1558023795722/joist/js/Screen.js?bust=1558027964641:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1558023795722/joist/js/Sim.js?bust=1558027964641:804:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1558023795722/joist/js/Sim.js?bust=1558027964641:812:27
id: Bayes Chrome
Approximately 5/16/2019, 12:23:15 PM
circuit-construction-kit-dc : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: numberZigZags must be an integer: 11.9947
Error: Assertion failed: numberZigZags must be an integer: 11.9947
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1558023795722/assert/js/assert.js:22:13)
    at Shape.zigZagToPoint (https://bayes.colorado.edu/continuous-testing/snapshot-1558023795722/kite/js/Shape.js?bust=1558027964641:353:17)
    at new FuseNode (https://bayes.colorado.edu/continuous-testing/snapshot-1558023795722/circuit-construction-kit-common/js/view/FuseNode.js?bust=1558027964641:63:10)
    at CircuitElementToolFactory.createFuseToolNode (https://bayes.colorado.edu/continuous-testing/snapshot-1558023795722/circuit-construction-kit-common/js/view/CircuitElementToolFactory.js?bust=1558027964641:324:9)
    at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1558023795722/circuit-construction-kit-dc/js/intro/view/IntroScreenView.js?bust=1558027964641:41:35)
    at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1558023795722/circuit-construction-kit-dc/js/intro/IntroScreen.js?bust=1558027964641:64:18)
    at IntroScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1558023795722/joist/js/Screen.js?bust=1558027964641:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1558023795722/joist/js/Sim.js?bust=1558027964641:804:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1558023795722/joist/js/Sim.js?bust=1558027964641:812:27
id: Bayes Chrome
Approximately 5/16/2019, 12:23:15 PM
```

**Comment by veillette** [comment]
The issue was related to FuseNode.js found in circuit-construction-kit-common and the new assertion added in Kite Shape (https://github.com/phetsims/faradays-law/issues/153).
I will monitor Bayes to see if more assertions are triggered.

**Comment by veillette** [comment]
It turns out to be related to the common repo of circuit-construction.
Closing this issue and tracking here (phetsims/circuit-construction-kit-common#496)
