### ISSUE TITLE
CT unable to find node from unique Trail id

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-dc#182]
```
circuit-construction-kit-dc : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/phet-io-wrappers/mirror-inputs/?sim=circuit-construction-kit-dc&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1596795593775%22%2C%22timestamp%22%3A1596797227273%7D
Uncaught Error: Assertion failed: unable to find node from unique Trail id
Error: Assertion failed: unable to find node from unique Trail id
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/assert/js/assert.js:22:13)
at Function.Trail.fromUniqueId (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/scenery/js/util/Trail.js:957:17)
at PDOMPointer.updateTrail (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/scenery/js/input/PDOMPointer.js:97:25)
at Input.updateTrailForPDOMDispatch (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/scenery/js/input/Input.js:1063:29)
at Input.focusinAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/scenery/js/input/Input.js:561:28)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/axon/js/Action.js:225:18)
at ActionIOImpl.implementation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/axon/js/ActionIO.js:68:35)
at PhetioCommandProcessor.processCommand (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/phet-io/js/phetioCommandProcessor.js:276:51)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/phet-io/js/phetioCommandProcessor.js:163:36
at Array.map (<anonymous>)
id: Bayes Chrome
Snapshot from 8/7/2020, 4:19:53 AM

----------------------------------

circuit-construction-kit-dc : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/phet-io-wrappers/mirror-inputs/?sim=circuit-construction-kit-dc&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1596795593775%22%2C%22timestamp%22%3A1596809815726%7D
Uncaught Error: Assertion failed: unable to find node from unique Trail id
Error: Assertion failed: unable to find node from unique Trail id
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/assert/js/assert.js:22:13)
at Function.Trail.fromUniqueId (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/scenery/js/util/Trail.js:957:17)
at PDOMPointer.updateTrail (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/scenery/js/input/PDOMPointer.js:97:25)
at Input.updateTrailForPDOMDispatch (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/scenery/js/input/Input.js:1063:29)
at Input.focusinAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/scenery/js/input/Input.js:561:28)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/axon/js/Action.js:225:18)
at ActionIOImpl.implementation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/axon/js/ActionIO.js:68:35)
at PhetioCommandProcessor.processCommand (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/phet-io/js/phetioCommandProcessor.js:276:51)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/phet-io/js/phetioCommandProcessor.js:163:36
at Array.map (<anonymous>)
id: Bayes Chrome
Snapshot from 8/7/2020, 4:19:53 AM

----------------------------------

circuit-construction-kit-dc : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/phet-io-wrappers/state/?sim=circuit-construction-kit-dc&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1596795593775%22%2C%22timestamp%22%3A1596796669101%7D
Uncaught Error: Assertion failed: countProperty should match array length.
Error: Assertion failed: countProperty should match array length.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/assert/js/assert.js:22:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/tandem/js/PhetioGroup.js:61:49
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/axon/js/TinyEmitter.js:69:53)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/axon/js/Property.js:273:25)
at PhaseCallback.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/axon/js/Property.js:323:47)
at PropertyStateHandler.attemptToApplyPhases (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/axon/js/PropertyStateHandler.js:264:41)
at PropertyStateHandler.undeferAndNotifyProperties (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/axon/js/PropertyStateHandler.js:198:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/axon/js/PropertyStateHandler.js:72:12
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/axon/js/Emitter.js:33:29
id: Bayes Chrome
Snapshot from 8/7/2020, 4:19:53 AM

----------------------------------

circuit-construction-kit-dc : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/phet-io-wrappers/state/?sim=circuit-construction-kit-dc&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1596795593775%22%2C%22timestamp%22%3A1596809994742%7D
Uncaught Error: Assertion failed: countProperty should match array length.
Error: Assertion failed: countProperty should match array length.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/assert/js/assert.js:22:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/tandem/js/PhetioGroup.js:61:49
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/axon/js/TinyEmitter.js:69:53)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/axon/js/Property.js:273:25)
at PhaseCallback.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/axon/js/Property.js:323:47)
at PropertyStateHandler.attemptToApplyPhases (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/axon/js/PropertyStateHandler.js:264:41)
at PropertyStateHandler.undeferAndNotifyProperties (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/axon/js/PropertyStateHandler.js:198:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/axon/js/PropertyStateHandler.js:72:12
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/axon/js/Emitter.js:33:29
id: Bayes Chrome
Snapshot from 8/7/2020, 4:19:53 AM

----------------------------------

circuit-construction-kit-dc : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/studio/?sim=circuit-construction-kit-dc&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1596795593775%22%2C%22timestamp%22%3A1596796667020%7D
Uncaught Error: phetioElement not found: circuitConstructionKitDc.labScreen.model.circuit.seriesAmmeters~0
Error: phetioElement not found: circuitConstructionKitDc.labScreen.model.circuit.seriesAmmeters~0
at window.assert (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/phet-io-wrappers/common/js/assert.js:32:13)
at Studio.onPhetioElementAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/studio/js/studio.js:238:19)
at phetioElementAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/studio/js/studio-main.js:44:10)
at Client.dispatch (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/phet-io-wrappers/common/js/Client.js:479:56)
at windowMessageListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596795593775/phet-io-wrappers/common/js/Client.js:348:26)
id: Bayes Chrome
Snapshot from 8/7/2020, 4:19:53 AM
```

**Comment by samreid** [comment]
Tracked in https://github.com/phetsims/circuit-construction-kit-common/issues/593, closing as duplicate.
