### ISSUE TITLE
CT cannot add a listener to a disposed TinyEmitter

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-dc#192]
```
circuit-construction-kit-dc : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630379878526/phet-io-wrappers/state/?sim=circuit-construction-kit-dc&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1630379878526%22%2C%22timestamp%22%3A1630382243468%7D
Uncaught Error: Uncaught Error: Assertion failed: Cannot add a listener to a disposed TinyEmitter
Error: Assertion failed: Cannot add a listener to a disposed TinyEmitter
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630379878526/assert/js/assert.js:25:13)
at TinyProperty.addListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630379878526/axon/js/TinyEmitter.js:113:15)
at TinyProperty.lazyLink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630379878526/axon/js/TinyProperty.js:170:10)
at NumberProperty.lazyLink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630379878526/axon/js/Property.js:392:23)
at new CircuitElementNumberControl (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630379878526/circuit-construction-kit-common/js/view/CircuitElementNumberControl.js:38:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630379878526/circuit-construction-kit-common/js/view/CircuitElementEditContainerNode.js:146:37
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630379878526/axon/js/TinyEmitter.js:86:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630379878526/axon/js/Property.js:271:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630379878526/axon/js/Property.js:186:14)
at ResistorNode.selectCircuitElementNodeWhenNear (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630379878526/circuit-construction-kit-common/js/view/CircuitElementNode.js:224:63)
id: Bayes Chrome
Snapshot from 8/30/2021, 9:17:58 PM
```

**Comment by samreid** [comment]
Moving to a common code repo so I can add to the milestone.
