### ISSUE TITLE
CT getLocalToGlobalMatrix unable to work for DAG

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-dc#197]
```
circuit-construction-kit-dc : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647574186761%22%2C%22timestamp%22%3A1647583694845%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed: getLocalToGlobalMatrix unable to work for DAG
Error: Assertion failed: getLocalToGlobalMatrix unable to work for DAG
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/assert/js/assert.js:25:13)
at HBox.getLocalToGlobalMatrix (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/scenery/js/nodes/Node.js:5728:17)
at HBox.localToGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/scenery/js/nodes/Node.js:5833:36)
at TrashButton.parentToGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/scenery/js/nodes/Node.js:5873:50)
at TrashButton.getGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/scenery/js/nodes/Node.js:5913:17)
at TrashButton.get globalBounds [as globalBounds] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/scenery/js/nodes/Node.js:5921:17)
at AnimatedPanZoomListener.keepNodeInView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/scenery/js/listeners/AnimatedPanZoomListener.js:860:72)
at displayFocusListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/scenery/js/listeners/AnimatedPanZoomListener.js:144:14)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/axon/js/Property.js:227:23)
id: Bayes Chrome
Snapshot from 3/17/2022, 9:29:46 PM

----------------------------------

circuit-construction-kit-dc : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647574186761%22%2C%22timestamp%22%3A1647579099769%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID already registered: circuitConstructionKitDc.labScreen.view.circuitNode.lightBulbNodeGroup.lightBulbNode_1
Error: Assertion failed: phetioID already registered: circuitConstructionKitDc.labScreen.view.circuitNode.lightBulbNodeGroup.lightBulbNode_1
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/assert/js/assert.js:25:13)
at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/phet-io/js/phetioEngine.js:631:36)
at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/phet-io/js/phetioEngine.js:1122:20)
at DynamicTandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/tandem/js/Tandem.js:156:36)
at CCKCLightBulbNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/tandem/js/PhetioObject.js:242:17)
at CCKCLightBulbNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/scenery/js/nodes/Node.js:6065:11)
at CCKCLightBulbNode.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/scenery/js/nodes/Node.js:6044:10)
at new Node (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/scenery/js/nodes/Node.js:500:12)
at new CircuitElementNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/circuit-construction-kit-common/js/view/CircuitElementNode.js:41:5)
at new FixedCircuitElementNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/circuit-construction-kit-common/js/view/FixedCircuitElementNode.js:57:5)
id: Bayes Chrome
Snapshot from 3/17/2022, 9:29:46 PM
```

**Comment by samreid** [comment]
This problem hasn't appeared on CT for a while, closing.
