### ISSUE TITLE
CT Cannot read properties of undefined (reading 'step')

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-dc#198]
```
circuit-construction-kit-dc : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653438441445/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1653438441445%22%2C%22timestamp%22%3A1653441720992%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'step')
TypeError: Cannot read properties of undefined (reading 'step')
at step (CircuitLayerNode.ts:604:105)
at Proxy.forEach
at forEach (CircuitLayerNode.ts:604:33)
at step (CCKCScreenView.ts:491:26)
at step (Sim.ts:471:18)
at apply (PhetioAction.ts:123:16)
at execute (Sim.ts:994:30)
at stepSimulation (Sim.ts:984:11)
at stepOneFrame (Sim.ts:959:11)
id: Bayes Chrome
Snapshot from 5/24/2022, 6:27:21 PM

----------------------------------

circuit-construction-kit-dc : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653438441445/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1653438441445%22%2C%22timestamp%22%3A1653460043732%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'step')
TypeError: Cannot read properties of undefined (reading 'step')
at step (CircuitLayerNode.ts:604:105)
at Proxy.forEach
at forEach (CircuitLayerNode.ts:604:33)
at step (CCKCScreenView.ts:491:26)
at step (Sim.ts:471:18)
at apply (PhetioAction.ts:123:16)
at execute (Sim.ts:994:30)
at stepSimulation (Sim.ts:984:11)
at stepOneFrame (Sim.ts:959:11)
id: Bayes Chrome
Snapshot from 5/24/2022, 6:27:21 PM
```

**Comment by samreid** [comment]
This problem hasn't appeared on CT for a while, closing.
