### ISSUE TITLE
PhET-iO Fuzz Testing: Cannot register two instances to same tandem id

### ISSUE THREAD

**Issue by zepumph** [phetsims/circuit-construction-kit-dc#42]
```js
circuit-construction-kit-dc
Uncaught Error: Assertion failed: Cannot register two different instances to the same id: circuitConstructionKitDc.introScreen.model.showLabelsProperty
Error: Assertion failed: Cannot register two different instances to the same id: circuitConstructionKitDc.introScreen.model.showLabelsProperty
    at window.assertions.assertFunction (http://localhost/assert/js/assert.js:21:13)
    at Object.addInstance (http://localhost/phet-io/js/phetio.js?bust=1494265562142:414:19)
    at Object.addInstance (http://localhost/phet-io/js/phetio.js?bust=1494265562142:57:14)
    at Tandem.addInstance (http://localhost/tandem/js/Tandem.js?bust=1494265562142:127:36)
    at BooleanProperty.Property [as constructor] (http://localhost/axon/js/Property.js?bust=1494265562142:101:38)
    at new BooleanProperty (http://localhost/axon/js/BooleanProperty.js?bust=1494265562142:44:14)
    at IntroScreenModel.CircuitConstructionKitModel [as constructor] (http://localhost/circuit-construction-kit-common/js/common/model/CircuitConstructionKitModel.js?bust=1494265562142:62:31)
    at new IntroScreenModel (http://localhost/circuit-construction-kit-dc/js/intro/model/IntroScreenModel.js?bust=1494265562142:20:33)
    at IntroScreen.createModel (http://localhost/circuit-construction-kit-dc/js/intro/IntroScreen.js?bust=1494265562142:36:16)
    at IntroScreen.initializeModel (http://localhost/joist/js/Screen.js?bust=1494265562142:198:26)

**Comment by samreid** [comment]
Thanks for the bug report, will you please see if it is fixed by the above commit?

**Comment by zepumph** [comment]
It did indeed! Now how about this one:

```js
circuit-construction-kit-dc
Uncaught Error: Assertion failed: Cannot register two different instances to the same id: circuitConstructionKitDc.introScreen.view.circuitElementToolbox.iconBattery
Error: Assertion failed: Cannot register two different instances to the same id: circuitConstructionKitDc.introScreen.view.circuitElementToolbox.iconBattery
    at window.assertions.assertFunction (http://localhost/assert/js/assert.js:21:13)
    at Object.addInstance (http://localhost/phet-io/js/phetio.js?bust=1494266668395:414:19)
    at Object.addInstance (http://localhost/phet-io/js/phetio.js?bust=1494266668395:57:14)
    at Tandem.addInstance (http://localhost/tandem/js/Tandem.js?bust=1494266668395:127:36)
    at Battery.CircuitElement [as constructor] (http://localhost/circuit-construction-kit-common/js/common/model/CircuitElement.js?bust=1494266668395:151:12)
    at Battery.FixedLengthCircuitElement [as constructor] (http://localhost/circuit-construction-kit-common/js/common/model/FixedLengthCircuitElement.js?bust=1494266668395:33:20)
    at new Battery (http://localhost/circuit-construction-kit-common/js/common/model/Battery.js?bust=1494266668395:34:31)
    at new CircuitElementToolbox (http://localhost/circuit-construction-kit-common/js/common/view/CircuitElementToolbox.js?bust=1494266668395:82:24)
    at IntroScreenView.CircuitConstructionKitScreenView [as constructor] (http://localhost/circuit-construction-kit-common/js/common/view/CircuitConstructionKitScreenView.js?bust=1494266668395:150:34)
    at new IntroScreenView (http://localhost/circuit-construction-kit-dc/js/intro/view/IntroScreenView.js?bust=1494266668395:22:38)
```

I am using aqua Fuzz Testing for phet-io to catch these, here is the link that I use:
http://localhost/aqua/test-server/test-sims.html?ea&audioVolume=0&testDuration=10000&testConcurrentBuilds=4&fuzzMouse&brand=phet-io&phetioStandalone&testSims=balloons-and-static-electricity,beers-law-lab,build-an-atom,capacitor-lab-basics,charges-and-fields,circuit-construction-kit-dc,color-vision,concentration,energy-skate-park-basics,faradays-law,forces-and-motion-basics,gravity-force-lab,john-travoltage,molecules-and-light,molarity,resistance-in-a-wire

**Comment by samreid** [comment]
Thanks!  Tests appear to be passing after recent commits (I forgot to link SHAs), can you double check?

**Comment by zepumph** [comment]
All looks good now. Thanks.
