### ISSUE TITLE
PhET-iO Fuzz testing errors

### ISSUE THREAD

**Issue by zepumph** [phetsims/circuit-construction-kit-dc#43]
```
circuit-construction-kit-dc
Uncaught Error: Assertion failed: Cannot register two different instances to the same id: circuitConstructionKitDc.exploreScreen.model.circuit.resistors_0
Error: Assertion failed: Cannot register two different instances to the same id: circuitConstructionKitDc.exploreScreen.model.circuit.resistors_0
    at window.assertions.assertFunction (http://localhost/assert/js/assert.js:21:13)
    at Object.addInstance (http://localhost/phet-io/js/phetio.js?bust=1495063293287:414:19)
    at Object.addInstance (http://localhost/phet-io/js/phetio.js?bust=1495063293287:57:14)
    at Tandem.addInstance (http://localhost/tandem/js/Tandem.js?bust=1495063293287:130:36)
    at Resistor.CircuitElement [as constructor] (http://localhost/circuit-construction-kit-common/js/common/model/CircuitElement.js?bust=1495063293287:153:12)
    at Resistor.FixedLengthCircuitElement [as constructor] (http://localhost/circuit-construction-kit-common/js/common/model/FixedLengthCircuitElement.js?bust=1495063293287:33:20)
    at new Resistor (http://localhost/circuit-construction-kit-common/js/common/model/Resistor.js?bust=1495063293287:32:31)
    at createResistor (http://localhost/circuit-construction-kit-common/js/common/view/CircuitElementToolbox.js?bust=1495063293287:173:14)
    at Object.down (http://localhost/circuit-construction-kit-common/js/common/view/CircuitElementToolNode.js?bust=1495063293287:55:32)
    at Input.dispatchToTargets (http://localhost/scenery/js/input/Input.js?bust=1495063293287:808:29)
circuit-construction-kit-dc
Uncaught Error: Assertion failed: Cannot register two different instances to the same id: circuitConstructionKitDc.exploreScreen.model.circuit.resistors_1
Error: Assertion failed: Cannot register two different instances to the same id: circuitConstructionKitDc.exploreScreen.model.circuit.resistors_1
    at window.assertions.assertFunction (http://localhost/assert/js/assert.js:21:13)
    at Object.addInstance (http://localhost/phet-io/js/phetio.js?bust=1495063293287:414:19)
    at Object.addInstance (http://localhost/phet-io/js/phetio.js?bust=1495063293287:57:14)
    at Tandem.addInstance (http://localhost/tandem/js/Tandem.js?bust=1495063293287:130:36)
    at Resistor.CircuitElement [as constructor] (http://localhost/circuit-construction-kit-common/js/common/model/CircuitElement.js?bust=1495063293287:153:12)
    at Resistor.FixedLengthCircuitElement [as constructor] (http://localhost/circuit-construction-kit-common/js/common/model/FixedLengthCircuitElement.js?bust=1495063293287:33:20)
    at new Resistor (http://localhost/circuit-construction-kit-common/js/common/model/Resistor.js?bust=1495063293287:32:31)
    at createResistor (http://localhost/circuit-construction-kit-common/js/common/view/CircuitElementToolbox.js?bust=1495063293287:173:14)
    at Object.down (http://localhost/circuit-construction-kit-common/js/common/view/CircuitElementToolNode.js?bust=1495063293287:55:32)
    at Input.dispatchToTargets (http://localhost/scenery/js/input/Input.js?bust=1495063293287:808:29)
circuit-construction-kit-dc
Uncaught Error: Assertion failed: Cannot register two different instances to the same id: circuitConstructionKitDc.introScreen.model.circuit.resistors_0
Error: Assertion failed: Cannot register two different instances to the same id: circuitConstructionKitDc.introScreen.model.circuit.resistors_0
    at window.assertions.assertFunction (http://localhost/assert/js/assert.js:21:13)
    at Object.addInstance (http://localhost/phet-io/js/phetio.js?bust=1495063293287:414:19)
    at Object.addInstance (http://localhost/phet-io/js/phetio.js?bust=1495063293287:57:14)
    at Tandem.addInstance (http://localhost/tandem/js/Tandem.js?bust=1495063293287:130:36)
    at Resistor.CircuitElement [as constructor] (http://localhost/circuit-construction-kit-common/js/common/model/CircuitElement.js?bust=1495063293287:153:12)
    at Resistor.FixedLengthCircuitElement [as constructor] (http://localhost/circuit-construction-kit-common/js/common/model/FixedLengthCircuitElement.js?bust=1495063293287:33:20)
    at new Resistor (http://localhost/circuit-construction-kit-common/js/common/model/Resistor.js?bust=1495063293287:32:31)
    at createResistor (http://localhost/circuit-construction-kit-common/js/common/view/CircuitElementToolbox.js?bust=1495063293287:173:14)
    at Object.down (http://localhost/circuit-construction-kit-common/js/common/view/CircuitElementToolNode.js?bust=1495063293287:55:32)
    at Input.dispatchToTargets (http://localhost/scenery/js/input/Input.js?bust=1495063293287:808:29)

**Comment by zepumph** [comment]
Here is one more I'm seeing from CCK-DC these days.

```
circuit-construction-kit-dc
Uncaught Error: Assertion failed: Cannot register two different instances to the same id: circuitConstructionKitDc.introScreen.view.wireResistivityControl
Error: Assertion failed: Cannot register two different instances to the same id: circuitConstructionKitDc.introScreen.view.wireResistivityControl
    at window.assertions.assertFunction (http://localhost/assert/js/assert.js:21:13)
    at Object.addInstance (http://localhost/phet-io/js/phetio.js?bust=1495225385270:414:19)
    at Object.addInstance (http://localhost/phet-io/js/phetio.js?bust=1495225385270:57:14)
    at Tandem.addInstance (http://localhost/tandem/js/Tandem.js?bust=1495225385270:128:36)
    at WireResistivityControl.setTandem (http://localhost/scenery/js/nodes/Node.js?bust=1495225385270:3468:22)
    at WireResistivityControl.set tandem [as tandem] (http://localhost/scenery/js/nodes/Node.js?bust=1495225385270:3473:32)
    at http://localhost/scenery/js/nodes/Node.js?bust=1495225385270:4764:25
    at u (http://localhost/sherpa/lib/lodash-4.17.4.min.js?bust=1495225385270:5:432)
    at Function.ru (http://localhost/sherpa/lib/lodash-4.17.4.min.js?bust=1495225385270:67:656)
    at WireResistivityControl.mutate (http://localhost/scenery/js/nodes/Node.js?bust=1495225385270:4751:9)

**Comment by samreid** [comment]
By the way, it is super fun watching CCK fuzz tests:

![image](https://cloud.githubusercontent.com/assets/679486/26383724/c52b28e0-3ff1-11e7-912a-253705679d11.png)

**Comment by samreid** [comment]
After the preceding commit, phet-io fuzz is passing on my machine.  Bayes will report if there are further problems.
